# Application Configuration:
headersv:
  # Listener Configuration params:
  network:
    networkId: "testnet"
    minPeers: 2
    maxPeers: 10
    peers:


  sync:
    headersToIgnore:

  storage:
    pruning:
      fork:
        enabled: false
        pruneAfterConfirmations: 7
      orphan:
        enabled: false
        pruneAfterInterval: 600